export const categories = [
    'Law Enforcement',
    'Administration',
    'Accounting',
    'Healthcare',
    'Education',
    'Work From Home',
    'IT',
    'Technology & IT',
    'Healthcare & Medical',
    'Banking',
    'Finance & Banking',
    'Education & Training',
    'Engineering',
    'Sales',
    'Sales & Marketing',
    'Human Resources',
    'Legal & Compliance',
    'Operations & Management',
    'Customer Support',
    'Customer Service',
    'Design & Creative',
    'SQL',
    'Oracle',
    'Graphic Design',
    'Digital Marketing',
    'Event Management',
    'Research & Development',
    'Manufacturing',
    'Retail & E-commerce',
    'Transportation & Logistics',
    'Real Estate',
    'Media & Communications',
    'Non-Profit & NGO',
    'Consulting'
  ];